# Generated by Django 4.2.5 on 2023-09-28 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrator', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=False)),
                ('faculty', models.CharField(choices=[('ทันตแพทย์', 'Dentistry'), ('พยาบาลศาสตร์', 'Nursing'), ('แพทยศาสตร์', 'Medicine'), ('เภสัชศาสตร์', 'Pharmaceutical Sciences'), ('ศึกษาศาสตร์', 'Education'), ('วิทยาศาสตร์', 'Science'), ('วิศวกรรมศาสตร์', 'Engineering'), ('สถาปัตยศาสตร์', 'Architecture'), ('นิเทศศาสตร์', 'Communication Arts'), ('นิติศาสตร์', 'Law')], default='null', max_length=128)),
                ('subjects', models.ManyToManyField(blank=True, related_name='list_Subjects', to='administrator.subject')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
