# Generated by Django 4.2.5 on 2023-09-27 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_student_id_alter_student_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='faculty',
            field=models.CharField(choices=[('ทันตแพทย์', 'Dentistry'), ('พยาบาลศาสตร์', 'Nursing'), ('แพทยศาสตร์', 'Medicine'), ('เภสัชศาสตร์', 'Pharmaceutical Sciences'), ('ศึกษาศาสตร์', 'Education'), ('วิทยาศาสตร์', 'Science'), ('วิศวกรรมศาสตร์', 'Engineering'), ('สถาปัตยศาสตร์', 'Architecture'), ('นิเทศศาสตร์', 'Communication Arts'), ('นิติศาสตร์', 'Law')], default='null', max_length=128),
        ),
    ]
