# Generated by Django 4.2.5 on 2023-09-27 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_remove_subject_id_subject_semester_subject_year_and_more'),
        ('users', '0004_student_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='list_Subjects', to='administrator.subject'),
        ),
    ]
