# Generated by Django 4.2.5 on 2023-09-28 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('name', models.CharField(max_length=64)),
                ('code', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('professor', models.CharField(max_length=128)),
                ('semester', models.CharField(choices=[('first', '1'), ('second', '2'), ('third', '3'), ('forth', '4'), ('fifth', '5'), ('summer', 'summer')], default='1', max_length=6)),
                ('year', models.CharField(default='2566', max_length=4)),
                ('quota', models.BooleanField(default=False)),
                ('seat', models.IntegerField()),
            ],
        ),
    ]
