# Generated by Django 4.2.5 on 2023-09-27 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='id',
        ),
        migrations.AddField(
            model_name='subject',
            name='semester',
            field=models.CharField(choices=[('first', '1'), ('second', '2'), ('third', '3'), ('forth', '4'), ('fifth', '5'), ('summer', 'summer')], default='1', max_length=6),
        ),
        migrations.AddField(
            model_name='subject',
            name='year',
            field=models.CharField(default='2566', max_length=4),
        ),
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(max_length=6, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subject',
            name='quota',
            field=models.BooleanField(default=False),
        ),
    ]
