# Generated by Django 4.2.5 on 2023-09-27 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_student_subjects'),
        ('administrator', '0002_remove_subject_id_subject_semester_subject_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='students',
            field=models.ManyToManyField(to='users.student'),
        ),
    ]
