# Generated by Django 4.2.5 on 2023-10-06 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='count_seat',
            field=models.IntegerField(default=0),
        ),
    ]
